Dev
IvanRodionovUgatu/project pull request #5
Opened 2023-03-13 12:47 UTC by IvanRodionovUgatu

2023-03-13 18:20 UTC, tanyaamiheeva requested changes

2023-03-13 18:20 UTC, tanyaamiheeva commented on rational.h
> +  void ReducePublic();
Это кто и зачем? Reduce в количестве одна штука должен быть только в private без всяких public-версий

2023-03-13 18:20 UTC, tanyaamiheeva commented on rational.h
> +  int q_ = 1;
Лучше отделять приватные поля от приватных методов пустой строкой

2023-03-13 18:20 UTC, tanyaamiheeva commented on rational.cpp
> +  bool fl_zn = false;
Это who? Дать более осмысленные названия переменным, чтобы было понятно, что в них лежит и за что этот флаг отвечает

2023-03-13 18:20 UTC, tanyaamiheeva commented on rational.cpp
> +    }
else? Зачем два if на одно условие?

2023-03-13 18:20 UTC, tanyaamiheeva commented on rational.cpp
> +  for (; i < len; ++i) {
Такие циклы лучше просто заменять на while - он для этого и существует)

2023-03-13 18:20 UTC, tanyaamiheeva commented on rational.cpp
> +    ++i;
++i происходит в любом случае, можно вынести из if

2023-03-14 11:23 UTC, IvanRodionovUgatu commented on rational.cpp
> +    ++i;
а если перед число не будет знака + или -, число будет проверяться неправильно из-за сдвига

2023-03-14 11:26 UTC, closed without merging

2023-03-14 11:26 UTC, tanyaamiheeva commented on rational.cpp
> +    ++i;
Я же не говорю установку флага выносить из if. У тебя в обоих случаях значение i на единицу увеличивается, какая разница тогда, чему равно s[0]? Если бы условие было как-то связано с i, тогда понятно, а здесь ты просто в любом случае увеличишь i на единицу и ничего больше не сделаешь с этой переменной

2023-03-14 11:38 UTC, tanyaamiheeva commented on rational.cpp
> +    ++i;
> а если перед число не будет знака + или -, число будет проверяться неправильно из-за сдвига

А, все, поняла, о чем ты. В таком кейсе да, согласна, но на будущее - если у тебя что-то повторяется в обоих ветках ифа и происходит в любом случае - нужно выносить